@set "PLATFORM=%1"

@set "PACKAGE_NAME=%PRODUCT_NAME%_%VERSION%_%PLATFORM%"
@set "UNCOMPRESSED_PLATFORMED_PACKAGE_DIR=%UNCOMPRESSED_PACKAGE_DIR%\%PLATFORM%"
@set "FINAL_PACKAGE_PATH=%FINAL_PACKAGE_DIR%\%PACKAGE_NAME%.7z"

:cleanup
rd /Q /S %UNCOMPRESSED_PLATFORMED_PACKAGE_DIR%
del /Q %FINAL_PACKAGE_PATH%

:compilation
msbuild /target:Rebuild /property:Configuration=Release /property:Platform=%PLATFORM% /property:BuildRoot="%COMPILATION_DIR%\\" ..\x3daudio1_7\x3daudio1_7.vcxproj

:copy_data
xcopy %COMPILATION_DIR%\%PLATFORM%\Release\*.dll %UNCOMPRESSED_PLATFORMED_PACKAGE_DIR%\
xcopy %HRTF_DATASET_DIR%\*.mhr %UNCOMPRESSED_PLATFORMED_PACKAGE_DIR%\hrtf\

:archive_data
7z a %FINAL_PACKAGE_PATH% %UNCOMPRESSED_PLATFORMED_PACKAGE_DIR%\*